# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b469ba5b1d104cbe899c83f6ab61c0559f73616be988a3c8de111045b25a061b2e326a2a0b073ec36451d865dcbd420c48727af35b4c3e2ee19fee6a52b6df1

test:
  secret_key_base: 6c5429f993059aac5a92d4d35418dcaa96616f25c7c6282de502bddc95d2ed2b5650681b00b2359912c3dcca3ebc825c70a1f890351fb0b304aa5f50acbd8852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
